version: "3"
services:
  server:
    image: nardzhiev/mafia_server
    hostname: MAFIA
    ports:
      - "8080:8080/tcp"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

